/* ----- Autogenerated by Django! Author: Zharikov Dimitry zdimon77@gmail.com --- */
// NGRX
import { Action } from '@ngrx/store';
// CRUD
import { QueryParamsModel } from '@core/_base/crud';
// Models
import { UserModel } from '../_models/user.model';
import { Update } from '@ngrx/entity';

export enum UserActionTypes {
    UserOnServerCreated = '[Edit User Component] User On Server Created',
    UserCreated = '[Edit User Component] User Created',
    UserUpdated = '[Edit User Component] User Updated',
    UsersStatusUpdated = '[User List Page] User Status Updated',
    OneUserDeleted = '[User List Page] One Video Deleted',
    ManyUsersDeleted = '[User List Page] Many Selected Users Deleted',
    UsersPageRequested = '[User List Page] Users Page Requested',
    UsersPageLoaded = '[User API] Users Page Loaded',
    UsersPageCancelled = '[User API] Users Page Cancelled',
    UsersPageToggleLoading = '[User] Users Page Toggle Loading',
    UsersActionToggleLoading = '[User] Users Action Toggle Loading'
}

export class UserOnServerCreated implements Action {
    readonly type = UserActionTypes.UserOnServerCreated;
    constructor(public payload: { user: UserModel }) { }
}

export class UserCreated implements Action {
    readonly type = UserActionTypes.UserCreated;
    constructor(public payload: { user: UserModel }) { }
}

export class UserUpdated implements Action {
    readonly type = UserActionTypes.UserUpdated;
    constructor(public payload: {
        partialUser: Update<UserModel>, // For State update
        results: UserModel // For Server update (through service)
    }) { }
}

export class UsersStatusUpdated implements Action {
    readonly type = UserActionTypes.UsersStatusUpdated;
    constructor(public payload: {
        results: UserModel[],
        status: number
    }) { }
}

export class OneUserDeleted implements Action {
    readonly type = UserActionTypes.OneUserDeleted;
    constructor(public payload: { id: number }) {}
}

export class ManyUsersDeleted implements Action {
    readonly type = UserActionTypes.ManyUsersDeleted;
    constructor(public payload: { ids: number[] }) {}
}

export class UsersPageRequested implements Action {
    readonly type = UserActionTypes.UsersPageRequested;
    constructor(public payload: { page: QueryParamsModel }) { }
}

export class UsersPageLoaded implements Action {
    readonly type = UserActionTypes.UsersPageLoaded;
    constructor(public payload: { results: UserModel[], totalCount: number, page: QueryParamsModel }) { }
}

export class UsersPageCancelled implements Action {
    readonly type = UserActionTypes.UsersPageCancelled;
}

export class UsersPageToggleLoading implements Action {
    readonly type = UserActionTypes.UsersPageToggleLoading;
    constructor(public payload: { isLoading: boolean }) { }
}

export class UsersActionToggleLoading implements Action {
    readonly type = UserActionTypes.UsersActionToggleLoading;
    constructor(public payload: { isLoading: boolean }) { }
}

export type UserActions = UserOnServerCreated
| UserCreated
| UserUpdated
| UsersStatusUpdated
| OneUserDeleted
| ManyUsersDeleted
| UsersPageRequested
| UsersPageLoaded
| UsersPageCancelled
| UsersPageToggleLoading
| UsersActionToggleLoading;
