# Generated by Django 2.2.4 on 2020-01-26 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_replenishmentlog_bonus_subscription'),
        ('webrtc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('session_status', models.BooleanField(default=0)),
                ('session_created_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.UserProfile')),
            ],
        ),
    ]
