# Generated by Django 2.2.4 on 2020-02-14 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0015_auto_20200213_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('text-chat', 'Text chat'), ('like', 'Like'), ('subscribe', 'Subscribe'), ('comment', 'Commnet'), ('block', 'Block')], default='text-chat', max_length=20)),
                ('object_id', models.IntegerField()),
                ('is_readed', models.BooleanField(default=False)),
                ('readed_at', models.DateTimeField()),
                ('abonent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_abonent', to='account.UserProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='account.UserProfile')),
            ],
        ),
    ]
