# Generated by Django 2.2.4 on 2019-12-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_agency2woman2paymenttype_komission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency2woman2paymenttype',
            old_name='komission',
            new_name='commission',
        ),
    ]
