# Generated by Django 2.2.4 on 2020-01-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatcontact_is_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
