# Generated by Django 2.2.4 on 2020-02-17 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='readed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.CharField(choices=[('text-chat', 'Text chat'), ('like', 'Like'), ('subscribe', 'Subscribe'), ('comment', 'Comment'), ('block', 'Block')], default='text-chat', max_length=20),
        ),
    ]
