/* ----- Autogenerated by Django! Author: Zharikov Dimitry zdimon77@gmail.com --- */
import { BaseModel } from '@core/_base/crud';


export class LogModel extends BaseModel {
    
        
            id: number;
        
    
        
            username: string;
        
    
        
            ip_address: string;
        
    
        
            type: string;
        
    
        
            created_at: string;
        
    

    clear() {
        
            
                
                
                    this.id = 0 ;
                
            
         
            
                
                    this.username = '' ;
                
                
            
         
            
                
                    this.ip_address = '' ;
                
                
            
         
            
                
                    this.type = '' ;
                
                
            
         
            
                
                    this.created_at = '' ;
                
                
            
         
    }
}
