# Generated by Django 2.2.4 on 2020-02-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='props',
            name='icon',
            field=models.ImageField(default='', upload_to='icons'),
            preserve_default=False,
        ),
    ]
