# Generated by Django 2.2 on 2020-03-12 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0002_props_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='props',
            name='category',
            field=models.CharField(default='', help_text='Category', max_length=250, verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='value',
            name='icon',
            field=models.ImageField(default='', upload_to='icons'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='value2user',
            name='text_value',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='value2user',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='props.Value'),
        ),
    ]
