# Generated by Django 2.2 on 2020-03-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0003_auto_20200312_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='props',
            name='type',
            field=models.CharField(choices=[('one', 'one'), ('many', 'many'), ('text', 'text'), ('date', 'date')], default='one', max_length=4, verbose_name='Type'),
        ),
    ]
