# Generated by Django 2.2.4 on 2019-12-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20191219_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu2user',
            name='can_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu2user',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu2user',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
    ]
