/* ----- Autogenerated by Django! Author: Zharikov Dimitry zdimon77@gmail.com --- */
import { BaseModel } from '@core/_base/crud';


export class UserGroupModel extends BaseModel {

    id: number;

    
        name: string;
    

    clear() {
        this.id = undefined;
        
            
                this.name = '' ;
            
            
         
    }
}
