/* ----- Autogenerated by Django! Author: Zharikov Dimitry zdimon77@gmail.com --- */
import { BaseModel } from '@core/_base/crud';


export class UserMediaModel extends BaseModel {

    id: number;

    
        get_small_url_square: string;
    
        role_media: string;
    

    clear() {
        this.id = undefined;
        
            
                this.get_small_url_square = '' ;
            
            
         
            
                this.role_media = '' ;
            
            
         
    }
}
