# Generated by Django 2.2.4 on 2019-12-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('detail_gallery', 'detail_gallery')], default='login', max_length=25, verbose_name='Type of message'),
        ),
    ]
