# Generated by Django 2.2.4 on 2019-12-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=250)),
                ('ip_address', models.CharField(db_index=True, max_length=250)),
                ('user_agent', models.CharField(db_index=True, max_length=250)),
                ('view_name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout')], default='login', max_length=25, verbose_name='Type of message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
