# Generated by Django 2.2.4 on 2019-12-04 15:45

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '__first__'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('about_me', models.TextField(help_text='About me', verbose_name='About me')),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='en', max_length=2, verbose_name='Language')),
                ('gender', models.CharField(choices=[('male', 'Man'), ('female', 'Woman')], db_index=True, default='male', max_length=6, verbose_name='Gender')),
                ('publicname', models.CharField(default='', max_length=250)),
                ('is_online', models.BooleanField(default=False)),
                ('account', models.IntegerField(default=0)),
                ('birthday', models.DateField(default='1999-01-01')),
                ('lookingfor', models.TextField(default='')),
                ('goal', models.TextField(default='')),
                ('job', models.TextField(default='')),
                ('city', models.CharField(default='', max_length=250)),
                ('country', django_countries.fields.CountryField(default='UA', max_length=2)),
                ('zodiac', models.CharField(default='', max_length=50)),
                ('is_camera', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ResetPasswordToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='When was this token generated')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Key')),
                ('ip_address', models.GenericIPAddressField(blank=True, default='', null=True, verbose_name='The IP address of this session')),
                ('user_agent', models.CharField(blank=True, default='', max_length=256, verbose_name='HTTP user Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='The User which is associated to this password reset token')),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.ReplanishmentPlan')),
                ('user_profile', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
            ],
        ),
    ]
