# Generated by Django 2.2.4 on 2019-12-18 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_merge_20191218_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginWarningHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_ok_ip_address', models.GenericIPAddressField()),
                ('current_warning_ip_address', models.GenericIPAddressField()),
                ('current_country', models.CharField(max_length=250)),
                ('current_city', models.CharField(blank=True, max_length=250)),
                ('full_current_location_info', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
            ],
        ),
    ]
