# Generated by Django 2.2.4 on 2019-12-25 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20191225_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='profile_docs')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='profile_docs')),
                ('first_name', models.CharField(default='', max_length=250)),
                ('last_name', models.CharField(default='', max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
            ],
            options={
                'verbose_name': 'Profile verify files',
                'verbose_name_plural': 'Profile verify file',
            },
        ),
    ]
