# Generated by Django 2.2.4 on 2019-12-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_userprofiledoc_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='1999-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofiledoc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='1999-01-01'),
            preserve_default=False,
        ),
    ]
