# Generated by Django 2.2.4 on 2020-01-09 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
        ('account', '0012_auto_20191225_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='replenishmentlog',
            name='bonus_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.BonusSubscription'),
        ),
    ]
