# Generated by Django 2.2.4 on 2019-12-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_loginwarninghistory'),
        ('account', '0004_merge_20191218_0748'),
    ]

    operations = [
    ]
