# Generated by Django 2.2.4 on 2019-12-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MailTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=250, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('title_ru', models.CharField(max_length=250, null=True)),
                ('title_en', models.CharField(max_length=250, null=True)),
                ('content', models.TextField(help_text='Content', verbose_name='Content')),
                ('content_ru', models.TextField(help_text='Content', null=True, verbose_name='Content')),
                ('content_en', models.TextField(help_text='Content', null=True, verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('alias', models.CharField(max_length=250)),
                ('type_obj', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='pictures')),
            ],
        ),
        migrations.CreateModel(
            name='ReplanishmentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dollar', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=0)),
            ],
        ),
    ]
