# Generated by Django 2.2.4 on 2019-12-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='adress',
            new_name='address',
        ),
    ]
