# Generated by Django 2.2.4 on 2019-12-20 12:30

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_userfeed_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfeedcomment',
            options={'ordering': ('tree_id', 'lft')},
        ),
        migrations.AddField(
            model_name='userfeedcomment',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfeedcomment',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfeedcomment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='feed.UserFeedComment'),
        ),
        migrations.AddField(
            model_name='userfeedcomment',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfeedcomment',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
