# Generated by Django 2.2.4 on 2019-12-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20191220_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfeedcomment',
            options={'ordering': ('tree_id', 'level', 'lft')},
        ),
    ]
