# Generated by Django 2.2.4 on 2020-01-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_userfeed_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedmedia',
            name='duration',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
