# Generated by Django 2.2.4 on 2020-02-04 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermedia', '0007_usermedia_feed'),
        ('feed', '0011_delete_userfeedmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeed',
            name='last_media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lastmedia', to='usermedia.UserMedia'),
        ),
    ]
