# Generated by Django 2.2.4 on 2019-12-09 09:33

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=250, verbose_name='Name')),
                ('director', models.CharField(max_length=250, verbose_name='Name and Surname of the Boss')),
                ('adress', models.TextField(help_text='Adress', max_length=250, verbose_name='Ardess of the office')),
                ('payment_method', models.CharField(choices=[('pb', 'Privatbank'), ('epay', 'Epay')], default='pb', max_length=50, verbose_name='Language')),
                ('contact_email', models.CharField(max_length=250, verbose_name='Email')),
                ('skype', models.CharField(default='', max_length=250, verbose_name='Email')),
                ('other_messanger', models.CharField(default='', help_text='Skype, telegram etc...', max_length=250, verbose_name='Other messangers')),
                ('country', models.CharField(default='', max_length=250, verbose_name='Country')),
                ('city', models.CharField(max_length=250, verbose_name='City')),
                ('phone1', models.CharField(default='', max_length=250, verbose_name='Phone 1')),
                ('phone2', models.CharField(default='', max_length=250, verbose_name='Phone 2')),
                ('term', models.CharField(max_length=250, verbose_name='Term of work')),
                ('is_approved', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
            },
        ),
        migrations.CreateModel(
            name='AgencyProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_type', models.CharField(choices=[('director', 'Director'), ('manager', 'Manager')], default='manager', max_length=50, verbose_name='Language')),
                ('name', models.CharField(help_text='Name', max_length=250, verbose_name='Name')),
                ('phone', models.CharField(default='', max_length=250, verbose_name='Phone')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Agency')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AgencyFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='agency_files')),
                ('video', models.FileField(blank=True, null=True, upload_to='agency_files')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Agency')),
            ],
            options={
                'verbose_name': 'Agency file',
                'verbose_name_plural': 'Agency files',
            },
        ),
        migrations.CreateModel(
            name='Agency2Woman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Agency')),
                ('woman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
            ],
            options={
                'verbose_name': 'Agency woman',
                'verbose_name_plural': 'Agency women',
            },
        ),
    ]
