from django.utils.translation import ugettext_lazy as _

MAP = {
    "TITLE_NAME": _('Name'),
    "TITLE_DATEBIRTH": _('Birthday'),
    "TITLE_ABOUT_ME": _('About me'),
    "TITLE_LOOKINGFOR": _('Looking for'),
    "TITLE_JOB": _('Job'),
    "TITLE_GOAL": _('Goal'),
    "TITLE_CITY": _('City'),
    "BUTTON_SUBMIT ": _('Submit'),
    "TITLE_EMAIL": _('Email'),
    "HELP_NAME": _('Enter your real name'),
    "HELP_ABOUT_ME": _('Something about you plz.'),
    "HELP_LOOKINGFOR": _('What is your ideal partner?'),
    "HELP_JOB": _('What do you do for your living?'),
    "HELP_GOAL": _('What is your altimate goal of your life :)?'),
    "HELP_CITY": _('City you are living in?'),
    "TITLE_RUSSIAN": _('Russian'),
    "TITLE_ENGLISH": _('English'),
    "HELP_EMAIL": _('Enter you email'),
    "TITLE_APP_NAME": _('Dating Club'),
    "TITLE_CHAT_NAME": _('Chat'),
    "TITLE_MY_PHOTO": _('My photo'),
    "TITLE_MY_VIDEO": _('My video'),
    "TITLE_MAILBOX": _('Mailbox'),
    "TITLE_ADD_CREDITS": _('Add credits'),
    "TITLE_AMMOUNT": _('Amount'),
    "TITLE_ADD": _('Add'),
    "TITLE_LOGOUT": _('Logout'),
    "TITLE_USERS_ONLINE": _('User online'),
    "TITLE_GALLERY": _('Gallery'),
    "TITLE_MY_CONTACTS": _('My contacts'),
    "TITLE_ADD_PHOTO": _('Add photo'),
    "BUTTON_SELECT_FILE": _('Select file'),
    "BUTTON_SETMAIN": _('Set main'),
    "BUTTON_DELETE": _('Delete'),
    "BUTTON_EDIT": _('Edit'),
    "LABEL_PHOTO_ISMAIN": _('Is main'),
    "LABEL_PHOTO_STATUS": _('Status'),
    "LABEL_PHOTO_ISDELETED": _('Deleted'),
    "BUTTON_TURNVIDEO": _('Turn video'),
    "BUTTON_TAKEPIC": _('Take picture'),
    "BUTTON_STOPVIDEO": _('Stop video'),
    # "": _(''),
}