# Generated by Django 2.2.4 on 2020-01-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonussubscription',
            name='bonus_level',
            field=models.CharField(choices=[(0, 'basic'), (1, 'normal'), (2, 'best')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='bonussubscription2paymenttype',
            name='limit_measurement',
            field=models.CharField(choices=[('times', 'times (usage counts)'), ('duration', 'duration (minutes)')], default='times', max_length=15),
        ),
    ]
