# Generated by Django 2.2.4 on 2020-01-11 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_replenishmentlog_bonus_subscription'),
        ('subscription', '0003_auto_20200110_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusSubscriptionUsedLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_much', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.BonusSubscription2PaymentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
            ],
        ),
    ]
