/* ----- Autogenerated by Django! Author: Zharikov Dimitry zdimon77@gmail.com --- */
// Angular
import { Component, OnInit, ChangeDetectionStrategy, OnDestroy, ChangeDetectorRef } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
// Material
import { MatDialog } from '@angular/material';
// RxJS
import { Observable, BehaviorSubject, Subscription, of } from 'rxjs';
import { map, startWith, delay, first } from 'rxjs/operators';
// NGRX
import { Store, select } from '@ngrx/store';
import { Dictionary, Update } from '@ngrx/entity';
import { AppState } from '../../../../../core/reducers';
// Layout
import { SubheaderService } from '../../../../../core/_base/layout';
// CRUD
import { LayoutUtilsService, MessageType, QueryParamsModel } from '../../../../../core/_base/crud';
// Services and Models
import {
	selectLastCreatedPlanId,
	selectPlanById,
	PlanModel,
	PlanOnServerCreated,
	PlanUpdated,
	PlanService
} from '../../store/';

const AVAILABLE_COLORS: string[] =
	['Red', 'CadetBlue', 'Gold', 'LightSlateGrey', 'RoyalBlue', 'Crimson', 'Blue', 'Sienna', 'Indigo', 'Green', 'Violet',
		'GoldenRod', 'OrangeRed', 'Khaki', 'Teal', 'Purple', 'Orange', 'Pink', 'Black', 'DarkTurquoise'];

const AVAILABLE_MANUFACTURES: string[] =
	['Pontiac', 'Subaru', 'Mitsubishi', 'Oldsmobile', 'Chevrolet', 'Chrysler', 'Suzuki', 'GMC', 'Cadillac', 'Mercury', 'Dodge',
		'Ram', 'Lexus', 'Lamborghini', 'Honda', 'Nissan', 'Ford', 'Hyundai', 'Saab', 'Toyota'];

@Component({
	// tslint:disable-next-line:component-selector
	selector: 'kt-plan-edit',
	templateUrl: './plan-edit.component.html',
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PlanEditComponent implements OnInit, OnDestroy {
	// Public properties
	plan: PlanModel;
	planId$: Observable<number>;
	oldPlan: PlanModel;
	selectedTab = 0;
	loadingSubject = new BehaviorSubject<boolean>(true);
	loading$: Observable<boolean>;
	planForm: FormGroup;
	hasFormErrors = false;
	filteredColors: Observable<string[]>;
	filteredManufactures: Observable<string[]>;
	// Private password
	private componentSubscriptions: Subscription;
	// sticky portlet header margin
	private headerMargin: number;

	/**
	 * Component constructor
	 *
	 * @param store: Store<AppState>
	 * @param activatedRoute: ActivatedRoute
	 * @param router: Router
	 * @param typesUtilsService: TypesUtilsService
	 * @param planFB: FormBuilder
	 * @param dialog: MatDialog
	 * @param subheaderService: SubheaderService
	 * @param layoutUtilsService: SubheaderService
	 * @param layoutConfigService: LayoutConfigService
	 * @param planService: PlansService
	 * @param cdr: ChangeDetectorRef
	 */
	constructor(
		private store: Store<AppState>,
		private activatedRoute: ActivatedRoute,
		private router: Router,
		private planFB: FormBuilder,
		public dialog: MatDialog,
		private subheaderService: SubheaderService,
		private layoutUtilsService: LayoutUtilsService,
		private planService: PlanService,
		private cdr: ChangeDetectorRef) {
	}

	/**
	 * @ Lifecycle sequences => https://angular.io/guide/lifecycle-hooks
	 */

	/**
	 * On init
	 */
	ngOnInit() {
		this.loading$ = this.loadingSubject.asObservable();
		this.loadingSubject.next(true);
		this.activatedRoute.params.subscribe(params => {
			const id = params.id;
			if (id && id > 0) {

				this.store.pipe(
					select(selectPlanById(id))
				).subscribe(result => {
					if (!result) {
						this.loadPlanFromService(id);
						return;
					}

					this.loadPlan(result);
				});
			} else {
				const newPlan = new PlanModel();
				newPlan.clear();
				this.loadPlan(newPlan);
			}
		});

		// sticky portlet header
		window.onload = () => {
			const style = getComputedStyle(document.getElementById('kt_header'));
			this.headerMargin = parseInt(style.height, 0);
		};
	}

	loadPlan(_plan, fromService: boolean = false) {
		if (!_plan) {
			this.goBack('');
		}
		this.plan = _plan;
		this.planId$ = of(_plan.id);
		this.oldPlan = Object.assign({}, _plan);
		this.initPlan();
		if (fromService) {
			this.cdr.detectChanges();
		}
	}

	// If product didn't find in store
	loadPlanFromService(planId) {
		this.planService.getPlanById(planId).subscribe(res => {
			this.loadPlan(res, true);
		});
	}

	/**
	 * On destroy
	 */
	ngOnDestroy() {
		if (this.componentSubscriptions) {
			this.componentSubscriptions.unsubscribe();
		}
	}

	/**
	 * Init product
	 */
	initPlan() {
		this.createForm();
		this.loadingSubject.next(false);
		this.subheaderService.setTitle('Edit Plan');
	}

	/**
	 * Create form
	 */
	createForm() {
		this.planForm = this.planFB.group({

			
			
				name: [this.plan.name, Validators.required],
		   
				dollar: [this.plan.dollar, Validators.required],
		   
				credit: [this.plan.credit, Validators.required],
		   
				curency: [this.plan.curency, Validators.required],
		   	

			/*
			manufacture: [this.product.manufacture, Validators.required],
			modelYear: [this.product.modelYear.toString(), Validators.required],
			mileage: [this.product.mileage, [Validators.required, Validators.pattern(/^-?(0|[1-9]\d*)?$/)]],
			description: [this.product.description],
			color: [this.product.color, Validators.required],
			price: [this.product.price, [Validators.required, Validators.pattern(/^-?(0|[1-9]\d*)?$/)]],
			condition: [this.product.condition.toString(), [Validators.required, Validators.min(0), Validators.max(1)]],
			status: [this.product.status.toString(), [Validators.required, Validators.min(0), Validators.max(1)]],
			VINCode: [this.product.VINCode, Validators.required]
			*/

		});

		/*
		this.filteredManufactures = this.planForm.controls.manufacture.valueChanges
			.pipe(
				startWith(''),
				map(val => this.filterManufacture(val.toString()))
			);
		this.filteredColors = this.productForm.controls.color.valueChanges
			.pipe(
				startWith(''),
				map(val => this.filterColor(val.toString()))
			);
		*/
	}

	/**
	 * Filter manufacture
	 *
	 * @param val: string
	 */

	 /*
	filterManufacture(val: string): string[] {
		return AVAILABLE_MANUFACTURES.filter(option =>
			option.toLowerCase().includes(val.toLowerCase()));
	}
	*/

	/**
	 * Filter color
	 *
	 * @param val: string
	 */
	/*
	filterColor(val: string): string[] {
		return AVAILABLE_COLORS.filter(option =>
			option.toLowerCase().includes(val.toLowerCase()));
	}
	*/
	/**
	 * Go back to the list
	 *
	 * @param id: any
	 */
	goBack(id) {
		this.loadingSubject.next(false);
		const url = `/plan/edit?id=${id}`;
		this.router.navigateByUrl(url, { relativeTo: this.activatedRoute });
	}

	goBackWithoutId() {
		this.router.navigateByUrl('/plan/list', { relativeTo: this.activatedRoute });
	}

	/**
	 * Refresh product
	 *
	 * @param isNew: boolean
	 * @param id: number
	 */
	refreshPlan(isNew: boolean = false, id = 0) {
		this.loadingSubject.next(false);
		let url = this.router.url;
		if (!isNew) {
			this.router.navigate([url], { relativeTo: this.activatedRoute });
			return;
		}

		url = `/ecommerce/products/edit/${id}`;
		this.router.navigateByUrl(url, { relativeTo: this.activatedRoute });
	}

	/**
	 * Reset
	 */
	reset() {
		this.plan = Object.assign({}, this.oldPlan);
		this.createForm();
		this.hasFormErrors = false;
		this.planForm.markAsPristine();
		this.planForm.markAsUntouched();
		this.planForm.updateValueAndValidity();
	}

	/**
	 * Save data
	 *
	 * @param withBack: boolean
	 */
	onSumbit(withBack: boolean = false) {
		this.hasFormErrors = false;
		const controls = this.planForm.controls;
		/** check form */
		if (this.planForm.invalid) {
			Object.keys(controls).forEach(controlName =>
				controls[controlName].markAsTouched()
			);

			this.hasFormErrors = true;
			this.selectedTab = 0;
			return;
		}

		// tslint:disable-next-line:prefer-const
		let editedPlan = this.preparePlan();

		if (editedPlan.id > 0) {
			this.updatePlan(editedPlan, withBack);
			return;
		}

		this.addPlan(editedPlan, withBack);
	}

	/**
	 * Returns object for saving
	 */
	preparePlan(): PlanModel {
		const controls = this.planForm.controls;
		const _plan = new PlanModel();
		_plan.id = this.plan.id;

		_plan.name = controls.name.value;

		_plan.dollar = controls.dollar.value;

		_plan.credit = controls.credit.value;

		_plan.curency = controls.curency.value;
			
		return _plan;
	}

	/**
	 * Add product
	 *
	 * @param _plan: PlanModel
	 * @param withBack: boolean
	 */
	addPlan(_plan: PlanModel, withBack: boolean = false) {
		this.loadingSubject.next(true);
		this.store.dispatch(new PlanOnServerCreated({ plan: _plan }));
		this.componentSubscriptions = this.store.pipe(
			delay(1000),
			select(selectLastCreatedPlanId)
		).subscribe(newId => {
			if (!newId) {
				return;
			}

			this.loadingSubject.next(false);
			if (withBack) {
				this.goBack(newId);
			} else {
				const message = `New Plan successfully has been added.`;
				this.layoutUtilsService.showActionNotification(message, MessageType.Create, 10000, true, true);
				this.refreshPlan(true, newId);
			}
		});
	}

	/**
	 * Update product
	 *
	 * @param _plan: PlanModel
	 * @param withBack: boolean
	 */
	updatePlan(_plan: PlanModel, withBack: boolean = false) {
		this.loadingSubject.next(true);

		const updatePlan: Update<PlanModel> = {
			id: _plan.id,
			changes: _plan
		};

		this.store.dispatch(new PlanUpdated({
			partialPlan: updatePlan,
			results: _plan
		}));

		
			if (withBack) {
				this.goBack(_plan.id);
			} else {
				const message = `Item successfully has been saved.`;
				this.layoutUtilsService.showActionNotification(message, MessageType.Update, 10000, true, true);
				this.refreshPlan(false);
			}
		
	}

	/**
	 * Returns component title
	 */
	getComponentTitle() {
		let result = 'Create Plan';
		if (!this.plan || !this.plan.id) {
			return result;
		}

		result = `Edit Plan`;
		return result;
	}

	/**
	 * Close alert
	 *
	 * @param $event
	 */
	onAlertClose($event) {
		this.hasFormErrors = false;
	}
}
