/* ----- Autogenerated by Django! Author: Zharikov Dimitry zdimon77@gmail.com --- */
import { BaseModel } from '@core/_base/crud';


export class PlanModel extends BaseModel {
    
        
            id: number;
        
    
        
            name: string;
        
    
        
            dollar: string;
        
    
        
            credit: string;
        
    
        
            curency: string;
        
    

    clear() {
        
            
                
                
                    this.id = 0 ;
                
            
         
            
                
                    this.name = '' ;
                
                
            
         
            
                
                    this.dollar = '' ;
                
                
            
         
            
                
                    this.credit = '' ;
                
                
            
         
            
                
                    this.curency = '' ;
                
                
            
         
    }
}
