# Generated by Django 2.2.4 on 2019-12-19 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='route',
            new_name='page',
        ),
    ]
