# Generated by Django 2.2.4 on 2019-12-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_merge_20191219_1026'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('liker', 'content_type', 'object_id')},
        ),
    ]
