# Generated by Django 2.2.4 on 2019-12-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20191223_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency2woman2paymenttype',
            name='komission',
            field=models.IntegerField(default=50),
        ),
    ]
