# Generated by Django 2.2.4 on 2020-01-10 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20200110_2335'),
        ('payment', '0004_auto_20191227_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.BonusSubscription'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reciver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciver', to='account.UserProfile'),
        ),
    ]
