# Generated by Django 2.2.4 on 2019-12-16 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20191215_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
