# Generated by Django 2.2.4 on 2019-12-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_userfeed_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeed',
            name='location',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
