# Generated by Django 2.2.4 on 2020-02-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_userfeed_last_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='1999-01-01'),
            preserve_default=False,
        ),
    ]
