# Generated by Django 2.2 on 2020-03-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_userfeedcomment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeed',
            name='is_stories',
            field=models.BooleanField(default=False),
        ),
    ]
