/* ----- Autogenerated by Django! Author: Zharikov Dimitry zdimon77@gmail.com --- */
// NGRX
import { createFeatureSelector, createSelector } from '@ngrx/store';
// Lodash
import { each } from 'lodash';
// CRUD
import { QueryResultsModel, HttpExtenstionsModel } from '@core/_base/crud';

// State
import { UserGroupState } from '../_reducers/user-group-list.tab.reducers';
import { UserGroupModel } from '../_models/user-group-list.tab.model';

export const selectUserGroupState = createFeatureSelector<UserGroupState>('UserGroup');

export const selectProductSpecificationById = (UserGroupId: number) => createSelector(
    selectUserGroupState,
    UserGroupState => UserGroupState.entities[UserGroupId]
);

export const selectUserGroupPageLoading = createSelector(
    selectUserGroupState,
    UserGroupState => UserGroupState.loading
);



export const selectLastCreatedUserGroupId = createSelector(
    selectUserGroupState,
    UserGroupState => UserGroupState.lastCreatedUserGroupId
);


export const selectPSShowInitWaitingMessage = createSelector(
    selectUserGroupState,
    UserGroupState => UserGroupState.showInitWaitingMessage
);




export const selectUserGroupInStore = createSelector(
    selectUserGroupState,
    UserGroupState => {
        const items: UserGroupModel[] = [];
        each(UserGroupState.entities, element => {
            items.push(element);
        });
        const httpExtension = new HttpExtenstionsModel();
        const result: UserGroupModel[] = httpExtension.sortArray(items, UserGroupState.lastQuery.sortField, UserGroupState.lastQuery.sortOrder);
        return new QueryResultsModel(result, UserGroupState.totalCount, '');
    }
);

