# Generated by Django 2.2.4 on 2019-12-04 15:47

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', image_cropping.fields.ImageCropField(blank=True, upload_to='user_photo')),
                ('cropping_port', image_cropping.fields.ImageRatioField('image', '150x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping port')),
                ('cropping_land', image_cropping.fields.ImageRatioField('image', '200x112', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping land')),
                ('cropping_square', image_cropping.fields.ImageRatioField('image', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping square')),
                ('croppos_port', models.CharField(default='', max_length=250)),
                ('croppos_land', models.CharField(default='', max_length=250)),
                ('croppos_square', models.CharField(default='', max_length=250)),
                ('video', models.FileField(blank=True, upload_to='user_video')),
                ('type_media', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=5, verbose_name='Type of media')),
                ('role_media', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('buffer', 'Buffer')], default='public', max_length=10, verbose_name='Role of media')),
                ('orient', models.CharField(choices=[('land', 'Landscape'), ('port', 'Portrait')], default='port', max_length=5, verbose_name='Orientation')),
                ('is_main', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
