# Generated by Django 2.2.4 on 2019-12-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermedia', '0003_auto_20191215_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedia',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermedia',
            name='geolocation',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermedia',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermedia',
            name='title',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
