# Generated by Django 2.2.4 on 2019-12-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermedia', '0004_auto_20191224_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedia',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
