# Generated by Django 2.2.4 on 2020-01-26 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_delete_userfeedmedia'),
        ('usermedia', '0006_usermedia_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedia',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedmedia', to='feed.UserFeed'),
        ),
    ]
