# Generated by Django 2.2.4 on 2020-03-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermedia', '0007_usermedia_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedia',
            name='to_the_stories',
            field=models.BooleanField(default=False),
        ),
    ]
