# Generated by Django 2.2.4 on 2020-03-04 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usermedia', '0008_usermedia_to_the_stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
