/* ----- Autogenerated by Django! Author: Zharikov Dimitry zdimon77@gmail.com --- */
// NGRX
import { createFeatureSelector, createSelector } from '@ngrx/store';
// Lodash
import { each } from 'lodash';
// CRUD
import { QueryResultsModel, HttpExtenstionsModel } from '@core/_base/crud';

// State
import { UserMediaState } from '../_reducers/user-media-list.tab.reducers';
import { UserMediaModel } from '../_models/user-media-list.tab.model';

export const selectUserMediaState = createFeatureSelector<UserMediaState>('UserMedia');

export const selectProductSpecificationById = (UserMediaId: number) => createSelector(
    selectUserMediaState,
    UserMediaState => UserMediaState.entities[UserMediaId]
);

export const selectUserMediaPageLoading = createSelector(
    selectUserMediaState,
    UserMediaState => UserMediaState.loading
);



export const selectLastCreatedUserMediaId = createSelector(
    selectUserMediaState,
    UserMediaState => UserMediaState.lastCreatedUserMediaId
);


export const selectPSShowInitWaitingMessage = createSelector(
    selectUserMediaState,
    UserMediaState => UserMediaState.showInitWaitingMessage
);




export const selectUserMediaInStore = createSelector(
    selectUserMediaState,
    UserMediaState => {
        const items: UserMediaModel[] = [];
        each(UserMediaState.entities, element => {
            items.push(element);
        });
        const httpExtension = new HttpExtenstionsModel();
        const result: UserMediaModel[] = httpExtension.sortArray(items, UserMediaState.lastQuery.sortField, UserMediaState.lastQuery.sortOrder);
        return new QueryResultsModel(result, UserMediaState.totalCount, '');
    }
);

