/* ----- Autogenerated by Django! Author: Zharikov Dimitry zdimon77@gmail.com --- */
import { forkJoin } from 'rxjs';
// Angular
import { Injectable } from '@angular/core';
// RxJS
import { mergeMap, map, tap } from 'rxjs/operators';
// NGRX
import { Effect, Actions, ofType } from '@ngrx/effects';
import { Store, Action } from '@ngrx/store';
// CRUD
import { QueryResultsModel, QueryParamsModel, DjangoQueryResultsModel } from '@core/_base/crud';
// Services
import { PlanService } from '../_services';
// State
import { AppState } from '@core/reducers';
// Actions
import {
    PlanActionTypes,
    PlansPageRequested,
    PlansPageLoaded,
    ManyPlansDeleted,
    OnePlanDeleted,
    PlansPageToggleLoading,
    PlansStatusUpdated,
    PlanUpdated,
    PlanCreated,
    PlanOnServerCreated
} from '../_actions/plan.actions';
import { defer, Observable, of } from 'rxjs';

@Injectable()
export class PlanEffects {
    showPageLoadingDistpatcher = new PlansPageToggleLoading({ isLoading: true });
    showLoadingDistpatcher = new PlansPageToggleLoading({ isLoading: true });
    hideActionLoadingDistpatcher = new PlansPageToggleLoading({ isLoading: false });

    @Effect()
    loadPlanPage$ = this.actions$
        .pipe(
            ofType<PlansPageRequested>(PlanActionTypes.PlansPageRequested),
            mergeMap(( { payload } ) => {
                this.store.dispatch(this.showPageLoadingDistpatcher);
                const requestToServer = this.plansService.findPlans(payload.page);
                const lastQuery = of(payload.page);
                return forkJoin(requestToServer, lastQuery);
            }),
            map(response => {
                const result: QueryResultsModel = response[0];
                const lastQuery: QueryParamsModel = response[1];
                // console.log(result);
                return new PlansPageLoaded({
                    results: result.results_list,
                    totalCount: result.totalCount,
                    page: lastQuery
                });
            }),
        );

    // @Effect()
    // deleteProduct$ = this.actions$
    //     .pipe(
    //         ofType<OneProductDeleted>(ProductActionTypes.OneProductDeleted),
    //         mergeMap(( { payload } ) => {
    //                 this.store.dispatch(this.showLoadingDistpatcher);
    //                 return this.productsService.deleteProduct(payload.id);
    //             }
    //         ),
    //         map(() => {
    //             return this.hideActionLoadingDistpatcher;
    //         }),
    //     );

    @Effect()
    deletePlans$ = this.actions$
        .pipe(
            ofType<ManyPlansDeleted>(PlanActionTypes.ManyPlansDeleted),
            mergeMap(( { payload } ) => {
                this.store.dispatch(this.showLoadingDistpatcher);
                return this.plansService.deletePlans(payload.ids);
                }
            ),
            map(() => {
                return this.hideActionLoadingDistpatcher;
            }),
        );

    // @Effect()
    // updateProductsStatus$ = this.actions$
    //     .pipe(
    //         ofType<ProductsStatusUpdated>(ProductActionTypes.ProductsStatusUpdated),
    //         mergeMap(( { payload } ) => {
    //             this.store.dispatch(this.showLoadingDistpatcher);
    //             return this.productsService.updateStatusForProduct(payload.products, payload.status);
    //         }),
    //         map(() => {
    //             return this.hideActionLoadingDistpatcher;
    //         }),
    //     );

    @Effect()
    updatePlan$ = this.actions$
        .pipe(
            ofType<PlanUpdated>(PlanActionTypes.PlanUpdated),
            mergeMap(( { payload } ) => {
                this.store.dispatch(this.showLoadingDistpatcher);
                return this.plansService.updatePlan(payload.results);
            }),
            map(() => {
                return this.hideActionLoadingDistpatcher;
            }),
        );

    @Effect()
    createPlan$ = this.actions$
        .pipe(
            ofType<PlanOnServerCreated>(PlanActionTypes.PlanOnServerCreated),
            mergeMap(( { payload } ) => {
                this.store.dispatch(this.showLoadingDistpatcher);
                return this.plansService.createPlan(payload.plan).pipe(
                    tap(res => {
                        this.store.dispatch(new PlanCreated({ plan: res }));
                    })
                );
            }),
            map(() => {
                return this.hideActionLoadingDistpatcher;
            }),
        );

    // // @Effect()
    // // init$: Observable<Action> = defer(() => {
    // //     const queryParams = new QueryParamsModel({});
    // //     return of(new ProductsPageRequested({ page: queryParams }));
    // // });

    constructor(private actions$: Actions, private plansService: PlanService, private store: Store<AppState>) { }
}
