# Generated by Django 2.2.4 on 2019-12-20 12:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_merge_20191219_1026'),
        ('blocklist', '0004_auto_20191217_1412'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blocklist',
            unique_together={('profile', 'block_by_user')},
        ),
    ]
