# Generated by Django 3.0.3 on 2020-02-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_status', models.SmallIntegerField(default=0)),
                ('api_status', models.SmallIntegerField(default=0)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(default='', max_length=1000)),
                ('time_create', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
