# Generated by Django 3.0.3 on 2020-02-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testwogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logserver',
            name='url_request',
            field=models.CharField(default='', max_length=200),
        ),
    ]
