# Generated by Django 3.0.3 on 2020-02-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testwogs', '0002_logserver_url_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='logserver',
            name='test_status',
            field=models.CharField(default='successfully', max_length=200),
        ),
    ]
