# Generated by Django 2.2.4 on 2020-02-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testwogs', '0004_auto_20200224_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logserver',
            old_name='message',
            new_name='alias',
        ),
        migrations.AddField(
            model_name='logserver',
            name='request',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='logserver',
            name='response',
            field=models.TextField(default=''),
        ),
    ]
