# Generated by Django 2.2.4 on 2020-02-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testwogs', '0005_auto_20200225_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='logserver',
            name='is_failed',
            field=models.BooleanField(default=True),
        ),
    ]
