# Generated by Django 2.2.4 on 2020-02-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testwogs', '0007_logserver_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logserver',
            name='is_failed',
        ),
        migrations.AddField(
            model_name='logserver',
            name='is_ok',
            field=models.BooleanField(default=False),
        ),
    ]
