# Generated by Django 2.2.4 on 2020-02-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testwogs', '0008_auto_20200226_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logserver',
            name='is_ok',
            field=models.BooleanField(default=True),
        ),
    ]
