# Generated by Django 2.2.4 on 2019-12-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderation',
            name='type_obj',
            field=models.CharField(choices=[('woman-profile', 'Woman profile'), ('man-profile', 'Man profile'), ('agency', 'Agency'), ('photo-new', 'New photo'), ('photo-delete', 'Delete photo'), ('video-new', 'New video'), ('video-delete', 'Delete video'), ('feed-new', 'New video'), ('feed-delete', 'Delete video'), ('video', 'Video'), ('verify-doc', 'Verification documents')], default='woman-profile', max_length=20, verbose_name='Object type'),
        ),
    ]
