/* ----- Autogenerated by Django! Author: Zharikov Dimitry zdimon77@gmail.com --- */
import { environment } from './../../../../../../environments/environment';
// Angular
import { Injectable } from '@angular/core';
import { HttpClient} from '@angular/common/http';
// RxJS
import { Observable, forkJoin } from 'rxjs';
import { map } from 'rxjs/operators';
// CRUD
import { HttpUtilsService, QueryParamsModel, QueryResultsModel } from '../../../../../core/_base/crud';
// Models and Consts
import { UserGroupModel } from '../_models/user-group-list.tab.model';
// import { SPECIFICATIONS_DICTIONARY } from '../_consts/specification.dictionary';

const API_LIST_URL = environment.apiUrl + '/account/user/group';
const API_CREATE_URL = environment.apiUrl + '/account/group/create';
const API_UPDATE_URL = environment.apiUrl + '/account/group/update';
const API_DELETE_URL = environment.apiUrl + '/account/group/delete';
// Real REST API
@Injectable()
export class UserGroupService {
	constructor(private http: HttpClient, private httpUtils: HttpUtilsService) { }

	// CREATE =>  POST: add a new product specification to the server
	createUserGroup(UserGroup): Observable<UserGroupModel> {
		return this.http.post<UserGroupModel>(API_CREATE_URL, UserGroup);
	}

	// READ
	// Server should return filtered specs by productId
	getAllUserGroupByUserGroupId(UserGroupId: number): Observable<UserGroupModel[]> {
		const url = API_LIST_URL + '/' + UserGroupId;
		return this.http.get<UserGroupModel[]>(url);
	}

	getUserGroupById(UserGroupId: number): Observable<UserGroupModel> {
		return this.http.get<UserGroupModel>(API_LIST_URL + `/${UserGroupId}`);
	}

	// Server should return sorted/filtered specs and merge with items from state
	findUserGroup(queryParams: QueryParamsModel, UserGroupId: number): Observable<QueryResultsModel> {
		const url = API_LIST_URL + '/' + UserGroupId;
		const body = {
			state: queryParams
		};
		// return this.http.post<QueryResultsModel>(url, body);
		return this.http.get<QueryResultsModel>(url);

	}

	// UPDATE => PUT: update the product specification on the server
	updateUserGroup(UserGroup: UserGroupModel): Observable<any> {
		return this.http.put(API_UPDATE_URL, UserGroup);
	}

	// DELETE => delete the product specification from the server
	deleteUserGroup(UserGroupId: number): Observable<any> {
		const url = `${API_DELETE_URL}/${UserGroupId}`;
		return this.http.delete<UserGroupModel>(url);
	}

	deleteManyUserGroup(ids: number[] = []): Observable<any> {
		const body = { UserGroupIdsForDelete: ids };
        return this.http.post<QueryResultsModel>(API_DELETE_URL, body);
	}

	getSpecs(): string[] {

        return [];

		// return SPECIFICATIONS_DICTIONARY;
	}
}
