# Generated by Django 2.2.4 on 2019-12-04 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_obj', models.CharField(choices=[('woman-profile', 'Woman profile'), ('man-profile', 'Man profile'), ('agency', 'Agency'), ('photo-new', 'New photo'), ('photo-delete', 'Delete photo'), ('video-new', 'New video'), ('video-delete', 'Delete video'), ('feed-new', 'New video'), ('feed-delete', 'Delete video'), ('video', 'Video')], default='woman-profile', max_length=20, verbose_name='Object type')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Name')),
                ('is_new', models.BooleanField(default=True, verbose_name='New or not?')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('data', models.TextField(default='[]')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='ModerationFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='moderation_files')),
                ('moderation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderation.Moderation')),
            ],
        ),
    ]
