# Generated by Django 2.2.4 on 2019-12-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191217_1229'),
        ('account', '0002_userprofile_lastname'),
    ]

    operations = [
    ]
