/* ----- Autogenerated by Django! Author: Zharikov Dimitry zdimon77@gmail.com --- */
// Angular
import { Injectable } from '@angular/core';
import { HttpParams, HttpHeaders } from '@angular/common/http';
// CRUD
import { QueryResultsModel } from '@core/_base/crud/models/query-models/query-results.model';
import { QueryParamsModel } from '@core/_base/crud/models/query-models/query-params.model';
import { HttpExtenstionsModel } from '@core/_base/crud/models/http-extentsions-model';

@Injectable()
export class HttpUtilsService {
    /**
     * Prepare query http params
     * @param queryParams: QueryParamsModel
     */
    getFindHTTPParams(queryParams): HttpParams {
        const offset = queryParams.pageSize*queryParams.pageNumber;
        let params = new HttpParams()


            .set('offset', offset.toString())
            .set('limit', queryParams.pageSize.toString());


            if(queryParams.filter.username !== undefined && queryParams.filter.username.length > 0) {
                params = params.set('username', queryParams.filter.username);
            }

            if(queryParams.filter.ip_address !== undefined && queryParams.filter.ip_address.length > 0) {
                params = params.set('ip_address', queryParams.filter.ip_address);
            }

            if(queryParams.filter.date_from !== undefined && queryParams.filter.date_from.length > 0) {
                params = params.set('date_from', queryParams.filter.date_from);
            }

            if(queryParams.filter.date_to !== undefined && queryParams.filter.date_to.length > 0) {
                params = params.set('date_to', queryParams.filter.date_to);
            }

            if(queryParams.filter.type !== undefined && queryParams.filter.type.length > 0) {
                params = params.set('type', queryParams.filter.type);
            }

        return params;
    }

    /**
     * get standard content-type
     */
    getHTTPHeaders(): HttpHeaders {
        const result = new HttpHeaders();
        result.set('Content-Type', 'application/json');
        return result;
    }

    baseFilter(_entities: any[], _queryParams: QueryParamsModel, _filtrationFields: string[] = []): QueryResultsModel {
        const httpExtention = new HttpExtenstionsModel();
        return httpExtention.baseFilter(_entities, _queryParams, _filtrationFields);
    }

    sortArray(_incomingArray: any[], _sortField: string = '', _sortOrder: string = 'asc'): any[] {
        const httpExtention = new HttpExtenstionsModel();
        return httpExtention.sortArray(_incomingArray, _sortField, _sortOrder);
    }

    searchInArray(_incomingArray: any[], _queryObj: any, _filtrationFields: string[] = []): any[] {
        const httpExtention = new HttpExtenstionsModel();
        return httpExtention.searchInArray(_incomingArray, _queryObj, _filtrationFields);
    }
}
