# Generated by Django 2.2.4 on 2019-12-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
        ('account', '0006_merge_20191219_1026'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='procent_for_agency',
            field=models.IntegerField(default=50, verbose_name='Procent for agency'),
        ),
        migrations.CreateModel(
            name='Agency2Woman2PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Agency')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.PaymentType')),
                ('woman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
            ],
            options={
                'verbose_name': 'Agency to woman and payment types',
                'verbose_name_plural': 'Agency to woman and payment types',
            },
        ),
    ]
