# Generated by Django 2.2.4 on 2020-01-15 16:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20200110_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ammount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Price'),
        ),
    ]
