/* ----- Autogenerated by Django! Author: Zharikov Dimitry zdimon77@gmail.com --- */
import { selectLogsInitWaitingMessage } from '../_selectors/log.selectors';
// RxJS
import { delay, distinctUntilChanged } from 'rxjs/operators';
// CRUD
import { DjangoQueryResultsModel, QueryResultsModel, BaseDataSource } from '@core/_base/crud';
// State
import { Store, select } from '@ngrx/store';
import { AppState } from '../../../../../core/reducers';
// Selectors
import { selectLogsInStore, selectLogsPageLoading } from '../_selectors/log.selectors';

export class LogsDataSource extends BaseDataSource {
    constructor(private store: Store<AppState>) {
        super();
        this.loading$ = this.store.pipe(
            select(selectLogsPageLoading)
        );

        this.isPreloadTextViewed$ = this.store.pipe(
            select(selectLogsInitWaitingMessage)
        );

        this.store.pipe(
            select(selectLogsInStore)
        ).subscribe((response: QueryResultsModel) => {
            this.paginatorTotalSubject.next(response.totalCount);
            this.entitySubject.next(response.items);
        });
    }
}
