# Generated by Django 2.2.4 on 2020-01-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20191221_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeed',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
