# Generated by Django 2.2.4 on 2020-01-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_userfeedmedia_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFeedMedia',
        ),
    ]
