# Generated by Django 2.2 on 2020-03-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_userfeed_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeed',
            name='geo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
