/* ----- Autogenerated by Django! Author: Zharikov Dimitry zdimon77@gmail.com --- */
import { forkJoin } from 'rxjs';
// Angular
import { Injectable } from '@angular/core';
// RxJS
import { mergeMap, map, tap } from 'rxjs/operators';
// NGRX
import { Effect, Actions, ofType } from '@ngrx/effects';
import { Store, Action } from '@ngrx/store';
// CRUD
import { QueryResultsModel, QueryParamsModel, DjangoQueryResultsModel } from '@core/_base/crud';
// Services
import { LogService } from '../_services';
// State
import { AppState } from '@core/reducers';
// Actions
import {
    LogActionTypes,
    LogsPageRequested,
    LogsPageLoaded,
    ManyLogsDeleted,
    OneLogDeleted,
    LogsPageToggleLoading,
    LogsStatusUpdated,
    LogUpdated,
    LogCreated,
    LogOnServerCreated
} from '../_actions/log.actions';
import { defer, Observable, of } from 'rxjs';

@Injectable()
export class LogEffects {
    showPageLoadingDistpatcher = new LogsPageToggleLoading({ isLoading: true });
    showLoadingDistpatcher = new LogsPageToggleLoading({ isLoading: true });
    hideActionLoadingDistpatcher = new LogsPageToggleLoading({ isLoading: false });

    @Effect()
    loadLogPage$ = this.actions$
        .pipe(
            ofType<LogsPageRequested>(LogActionTypes.LogsPageRequested),
            mergeMap(( { payload } ) => {
                this.store.dispatch(this.showPageLoadingDistpatcher);
                const requestToServer = this.logsService.findLogs(payload.page);
                const lastQuery = of(payload.page);
                return forkJoin(requestToServer, lastQuery);
            }),
            map(response => {
                const result: QueryResultsModel = response[0];
                const lastQuery: QueryParamsModel = response[1];
                // console.log(result);
                return new LogsPageLoaded({
                    results: result.results_list,
                    totalCount: result.totalCount,
                    page: lastQuery
                });
            }),
        );

    // @Effect()
    // deleteProduct$ = this.actions$
    //     .pipe(
    //         ofType<OneProductDeleted>(ProductActionTypes.OneProductDeleted),
    //         mergeMap(( { payload } ) => {
    //                 this.store.dispatch(this.showLoadingDistpatcher);
    //                 return this.productsService.deleteProduct(payload.id);
    //             }
    //         ),
    //         map(() => {
    //             return this.hideActionLoadingDistpatcher;
    //         }),
    //     );

    @Effect()
    deleteLogs$ = this.actions$
        .pipe(
            ofType<ManyLogsDeleted>(LogActionTypes.ManyLogsDeleted),
            mergeMap(( { payload } ) => {
                this.store.dispatch(this.showLoadingDistpatcher);
                return this.logsService.deleteLogs(payload.ids);
                }
            ),
            map(() => {
                return this.hideActionLoadingDistpatcher;
            }),
        );

    // @Effect()
    // updateProductsStatus$ = this.actions$
    //     .pipe(
    //         ofType<ProductsStatusUpdated>(ProductActionTypes.ProductsStatusUpdated),
    //         mergeMap(( { payload } ) => {
    //             this.store.dispatch(this.showLoadingDistpatcher);
    //             return this.productsService.updateStatusForProduct(payload.products, payload.status);
    //         }),
    //         map(() => {
    //             return this.hideActionLoadingDistpatcher;
    //         }),
    //     );

    @Effect()
    updateLog$ = this.actions$
        .pipe(
            ofType<LogUpdated>(LogActionTypes.LogUpdated),
            mergeMap(( { payload } ) => {
                this.store.dispatch(this.showLoadingDistpatcher);
                return this.logsService.updateLog(payload.results);
            }),
            map(() => {
                return this.hideActionLoadingDistpatcher;
            }),
        );

    @Effect()
    createLog$ = this.actions$
        .pipe(
            ofType<LogOnServerCreated>(LogActionTypes.LogOnServerCreated),
            mergeMap(( { payload } ) => {
                this.store.dispatch(this.showLoadingDistpatcher);
                return this.logsService.createLog(payload.log).pipe(
                    tap(res => {
                        this.store.dispatch(new LogCreated({ log: res }));
                    })
                );
            }),
            map(() => {
                return this.hideActionLoadingDistpatcher;
            }),
        );

    // // @Effect()
    // // init$: Observable<Action> = defer(() => {
    // //     const queryParams = new QueryParamsModel({});
    // //     return of(new ProductsPageRequested({ page: queryParams }));
    // // });

    constructor(private actions$: Actions, private logsService: LogService, private store: Store<AppState>) { }
}
